### PR TITLE
Explain how to use "custom path checkbox"

### PR DESCRIPTION
**Pull request by pedrorocha-net**
Follow up from the discussion on https://github.com/md-systems/pathauto/issues/59

### CODE REVIEW

**Comment by Berdir** [comment]
Thanks for starting this!

I would word it a bit differently. Almost everyone is "in need" of that, so I'd leave wording like that out. I'd just make it very specific and start with a title that explicitly says what it is about. "Enabling the checkbox to use a custom alias".

It is also worth mentioning that this problem only happens for pre-existing node types, if you create a new one in the UI then it will use the pathauto widget by default.

**Comment by pedrorocha-net** [comment]
Agree about the text, but thinking more about it, I have a question: do you agree that probably most websites will install path auto after having most of the content types already defined, and specially for other entity types(e.g. User).

Maybe it would be better to focus on changing all of the widgets on module install? It'll take more time to do than create this text, naturally, but probably more useful, specially for users coming from D7, that doesn't require this step.

**Comment by Berdir** [comment]
You're not wrong, I thought of this as a workaround until we have a better fix. Yes, it would be nice to have that.

Are you in Barcelona. I'm in the general sprint room, if you want to implement the automated updating and have questions about it.

**Comment by pedrorocha-net** [comment]
Yes, i'm here too, but don't know who you are..hehe
On what table are you?

**Comment by Berdir** [comment]
Different approach: https://github.com/md-systems/pathauto/pull/83

No need to document anything anymore with that, as we just replace the used class, without any need for manual or automated re-configuration.

**Pull request closed without merging**
