### PR TITLE
Pattern config entities simplified ui

### PR DESCRIPTION
**Pull request by Berdir**

### CODE REVIEW

**Comment by juampynr** [comment]
:japanese_ogre:

How can I help peer reviewing this?

**Comment by Berdir** [comment]
Currently going through and doing some cleanup. Will possibly merge this soon.

Note: I am using the new token entity mapper service. Make sure you are using the latest token 8.x-1.x.

**Comment by Berdir** [comment]
Ok, going to merge this now!

A few follow-ups to work on:
- Make pathauto_entity_base_field_info() configurable. Expose a list of checkboxes for each type. Ticking the checkbox should expose that base field for the selected entity types. In case a base field already exists and is not defined by us (e.g. node), it should be checked by default and be disabled. This in turn will then automatically expose a alias type plugin. At this point, we'll have achieved the goal of fully  generic and automated integration with any entity type.
- Decide about removing or keeping hook_pathauto_pattern_alter(), I'm considering to remove it, we can add it back if there is a use case.
- Update and test forum related code
- Introduce a method on pattern plugins to react to alias generation, so that we can move the condition code in updateEntityAlias() to a taxonomy term alias type plugin

**Comment by juampynr** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by balsama** [comment]
Nice! HUGE step in the right direction. Thanks!

**Pull request merged**
