### PR TITLE
Upgrade to drupal_ti 1.3.0, which supports sudo: false, sync dist file.

### PR DESCRIPTION
**Pull request by fabianx-ai**

### CODE REVIEW

**Comment by fabianx-ai** [comment]
@Berdir ^^ :-D

**Comment by Berdir** [comment]
Interesting, I'd expect this to be faster but it doesn't really seem to be?

https://travis-ci.org/md-systems/pathauto/builds/70931843
Test run time: 1m45/1m58 (not the build, just the simpletests)

https://travis-ci.org/md-systems/pathauto/builds/71042616
Test run time: 2m25/2m54 (and 42s for PHP7, which is now passing, nice!)

**Comment by fabianx-ai** [comment]
The biggest speed-up comes that we can

a) Use caching (coming in 1.3.1 or 1.3.2 likely) [ 19 s test run with phpunit! ]
b) Probably due to 4 GB memory and bigger CPU can use a higher concurrency level.

I will experiment some with the concurrency level.

**Comment by fabianx-ai** [comment]
hhvm is currently broken in D8 Core (we probably miss some class or so?), but would besides that probably work.

**Comment by fabianx-ai** [comment]
Seems concurrency 4 wins, 2 min 10 sec for 5.5, concurrency 8 was way slower (3 min 30 s). So seems the docker ones are on average faster.

**Comment by fabianx-ai** [comment]
I will squash the commits to avoid polluting history.

**Pull request merged**
