### PR TITLE
Rebuild routes to allow Pathauto in profiles.

### PR DESCRIPTION
**Pull request by alex-mccabe**
https://github.com/md-systems/pathauto/issues/42

### CODE REVIEW

**Comment by Berdir** [comment]
What kind of content is created and how in that install profile?

I'm using the default_content project from larowlan and since that uses serialization, it requires the routes to be present anyway, so I did a router rebuild in the hook_install() of my module that provides content. Seems a lot cleaner than doing it here...

**Comment by alex-mccabe** [comment]
user/1 is created, for one thing.

**Comment by Berdir** [comment]
That's true, but that does happen earlier. But guess a resave happens at some point before the routes are rebuilt.

How are you installing, drush? The module installer does call setRebuildNeeded() and that should do it and the end of the request. but drush is different.

Can we make try/catch specific to the thrown exception? Then I'm OK with merging it.

**Comment by Berdir** [comment]
What I said in https://github.com/md-systems/pathauto/issues/42

**Pull request closed without merging**
