### PR TITLE
testing with latest PHP and PHP7 nightly releases

### PR DESCRIPTION
**Pull request by ghost**
Travis CI has PHP builds for latest stable version of PHP i.e. 5.6 and also the nightly releases of PHP7. Added hhvm in the mix too, if failed in PHP7 or hhvm it'll not generate error, but will help in long term to check how **Drupal8** and specially **pathauto** fares with latest PHPs.

### CODE REVIEW

**Comment by Berdir** [comment]
Thanks. Adding PHP7 and hhvm is very interesting, but looking at the results, they both fail already in the testbot setup. That's not too useful. IMHO we should either at least configure it so that it works for them or open a separate pull request to add those.

**Comment by ghost** [comment]
yes I noticed `$(phpenv version-name)` command fails for _php nightly_ and _hhvm_. I will look around the solution and add commit in the same PR.

**Comment by Berdir** [comment]
We're now using drupal_ti and the tests on php7 are actually running and passing :)

**Comment by ghost** [comment]
:+1:  great to hear that....

**Pull request closed without merging**
